wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.10
    cli_version: 0.22.1
    framework: huggingface
    huggingface_version: 4.53.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1759311074
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 71
      - 77
      - 103
      - 105
      - 106
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 71
      - 77
      - 103
      - 105
      - 106
      3:
      - 4
      - 7
      - 13
      - 42
      - 66
      4: 3.12.10
      5: 0.22.1
      6: 4.53.0.dev0
      13: linux-x86_64
    e:
      hvo53l815ftfhirwe4n5udky9047xunu:
        os: Linux-5.14.0-427.76.1.el9_4.x86_64-x86_64-with-glibc2.34
        python: CPython 3.12.10
        started_at: '2025-10-01T09:31:14.178128Z'
        args:
        - +trainer.fast_dev_run=False
        - trainer.accelerator=gpu
        - trainer.devices=4
        - trainer.num_nodes=1
        - +trainer.log_every_n_steps=5
        - data=qm9
        - data.batch_size=1024
        - data.datadir=/lustre/fsn1/projects/rech/aik/ukf79qj/data/qm9
        - data.max_epochs=500
        - general.conditioning=True
        - general.checkpoint_path=null
        - lightning_module/module/denoising_module=mixed_attention_gtf
        - lightning_module/module/loss_functions=CE_train_VLB_val
        program: /lustre/fswork/projects/rech/aik/ukf79qj/programs/GASP-DIFF/gasp_diff/scripts/train.py
        root: .
        host: r7i5n2
        executable: /lustre/fshomisc/sup/hpe/pub/miniforge/24.11.3/envs/pytorch-gpu-2.7.0+py3.12.10/bin/python
        cpu_count: 40
        cpu_count_logical: 80
        gpu_type: Tesla V100-SXM2-32GB
        gpu_count: 4
        disk:
          /:
            total: '100277387264'
            used: '10249572352'
        memory:
          total: '200554774528'
        gpu_nvidia:
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-f2c74a00-a748-2a8c-b9bd-604d158a89ba
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-90330e27-64f2-d66d-c618-a966dc58bfd1
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-bdd029ad-3e0d-ba4c-ba0f-1982bc34d6a3
        - name: Tesla V100-SXM2-32GB
          memory_total: '34359738368'
          cuda_cores: 5120
          architecture: Volta
          uuid: GPU-c7d132b1-1ca5-f8aa-ffc2-398ae0022f51
        cuda_version: '12.8'
        slurm:
          step_launcher_port: '62914'
          ntasks_per_node: '4'
          cpu_bind_type: 'mask_cpu:'
          prio_process: '0'
          job_user: ukf79qj
          cpus_on_node: '80'
          script_context: prolog_task
          topology_addr: r7i5n2
          mem_per_cpu: '4000'
          stepid: '0'
          job_gid: '302796'
          nnodes: '1'
          cluster_name: jean-zay
          localid: '0'
          umask: '0027'
          topology_addr_pattern: node
          jobid: '150508'
          step_gpus: 0,1,2,3
          nodeid: '0'
          task_pid: '2250835'
          step_nodelist: r7i5n2
          job_nodelist: r7i5n2
          submit_dir: /lustre/fswork/projects/rech/aik/ukf79qj/programs/scripts
          distribution: block
          job_name: GASP-DIFF-MED
          srun_comm_host: 10.148.0.87
          job_num_nodes: '1'
          job_cpus_per_node: '40'
          conf: /etc/slurm/slurm.conf
          tasks_per_node: '4'
          pmixp_abort_agent_port: '62913'
          step_num_nodes: '1'
          cpu_bind_list: 0x000000000000000003FF,0x000000000000000FFC00,0x0000000000003FF00000,0x0000000000FFC0000000
          srun_comm_port: '62914'
          job_start_time: '1759311025'
          job_id: '150508'
          job_partition: gpu_p13
          step_num_tasks: '4'
          job_qos: qos_gpu-t3
          procid: '0'
          step_tasks_per_node: '4'
          cpu_bind_verbose: quiet
          hint: nomultithread
          cpu_bind: quiet,mask_cpu:0x000000000000000003FF,0x000000000000000FFC00,0x0000000000003FF00000,0x0000000000FFC0000000
          mpi_type: pmix_v3
          job_gpus: 0,1,2,3
          gtids: 0,1,2,3
          nprocs: '4'
          cpus_per_task: '10'
          nodelist: r7i5n2
          submit_host: jean-zay2
          job_end_time: '1759318225'
          threads_per_core: '1'
          ntasks: '4'
          job_account: aik@v100
          gpus_on_node: '4'
          tres_per_task: cpu:10
          job_uid: '305211'
          step_id: '0'
          step_resv_ports: 14306-14310
          launch_node_ipaddr: 10.148.0.87
          pmix_mapping_serv: (vector,(0,1,4))
        writer_id: hvo53l815ftfhirwe4n5udky9047xunu
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: loss_train_step
      5: 1
      6:
      - 1
    - 1: batch_CE_nodes_train_step
      5: 1
      6:
      - 1
    - 1: batch_CE_global_features_train_step
      5: 1
      6:
      - 1
    - 1: batch_CE_edges_train_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: loss_train_epoch
      5: 1
      6:
      - 1
    - 1: batch_CE_edges_train_epoch
      5: 1
      6:
      - 1
    - 1: batch_CE_nodes_train_epoch
      5: 1
      6:
      - 1
    - 1: batch_CE_global_features_train_epoch
      5: 1
      6:
      - 1
    - 1: batch_VLB_nodes_validation
      5: 1
      6:
      - 1
    - 1: batch_VLB_edges_validation
      5: 1
      6:
      - 1
    - 1: loss_validation
      5: 1
      6:
      - 1
